Optimize/Controllers/PolicyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Optimize.Controllers
{
    public class PolicyController : Controller
    {
        // GET: Policy
        public ActionResult Index()
        {
            return View();
        }
    }
}

Optimize/Views/Shared/_SiteLayout.cshtml
<!DOCTYPE html>
<html class="wide wow-animation" lang="en">
<head>
    <title>@ViewBag.Title - Optimize</title>
    <meta name="viewport" content="width=device-width height=device-height initial-scale=1.0">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="shortcut icon" href="~/Content/images/favicon.ico" type="image/x-icon">
    <link rel="icon" href="~/Content/images/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CMuli:100,300,400,600,800">
    @Styles.Render("~/Content/css-all")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <style>
        .ie-panel {
            display: none;
            background: #212121;
            padding: 10px 0;
            box-shadow: 3px 3px 5px 0 rgba(0,0,0,.3);
            clear: both;
            text-align: center;
            position: relative;
            z-index: 1;
        }

        html.ie-10 .ie-panel, html.lt-ie-10 .ie-panel {
            display: block;
        }
    </style>
    <div class="ie-panel"><a href="http://windows.microsoft.com/en-US/internet-explorer/"><img src="~/Content/images/ie8-panel/warning_bar_0000_us.jpg" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today."></a></div>
    <div class="preloader" id="loading">
        @*<img src="~/Content/images/preloader.gif" />*@
        <div class="preloader-body">

            <div id="loading-center-object">

                <div class="object" id="Optimize"></div>
                <div class="object" id="object_three"></div>
                <div class="object" id="object_two"></div>
                <div class="object" id="object_one"></div>
            </div>
        </div>
    </div>
    <div class="page">
        @using Optimize.Models.Helper;
        <!-- Page Header-->
        <header class="section page-header">
            <!-- RD Navbar-->
            <div class="rd-navbar-wrap">
                <nav class="rd-navbar rd-navbar-classic" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-md-layout="rd-navbar-fixed" data-md-device-layout="rd-navbar-fixed" data-lg-layout="rd-navbar-fixed" data-lg-device-layout="rd-navbar-fixed" data-xl-layout="rd-navbar-static" data-xl-device-layout="rd-navbar-static" data-xxl-layout="rd-navbar-static" data-xxl-device-layout="rd-navbar-static" data-lg-stick-up-offset="0px" data-xl-stick-up-offset="0px" data-xxl-stick-up-offset="0px" data-lg-stick-up="true" data-xl-stick-up="true" data-xxl-stick-up="true">
                    <div class="rd-navbar-main">
                        <!-- RD Navbar Panel-->
                        <div class="rd-navbar-panel">
                            <!-- RD Navbar Toggle-->
                            <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav-wrap"><span></span></button>
                            <!-- RD Navbar Brand-->
                            <div class="rd-navbar-brand">
                                <a class="brand" href="/Home">
                                    <img class="brand-logo-dark" src="~/Content/images/bluegradient logo.png" alt="Optimize" style="height:65px; margin-top:-4px;" />
                                </a>
                                <!--width="113" height="38"-->
                            </div>
                        </div>
                        <div class="rd-navbar-nav-wrap">
                            <p class="rd-navbar-slogan">En annorlunda IT partner</p>
                            <!-- RD Navbar Nav-->
                            <ul class="rd-navbar-nav">
                                <li class="rd-nav-item">@Html.NavigationLink("Hem", "Index", "Home", "rd-nav-link")</li>

                                <li class="rd-nav-item">@Html.NavigationLink("Om oss", "Index", "About", "rd-nav-link")</li>
                                @*<li class="rd-nav-item">@Html.NavigationLink("Services", "Index", "Services", "rd-nav-link")</li>*@
                            <li class="rd-nav-item rd-navbar--has-dropdown rd-navbar-submenu">

                                <a class="rd-nav-link" href="#">Tjänster</a>
                                <!-- RD Navbar Dropdown-->
                                <ul class="rd-menu rd-navbar-dropdown">
                                    <li class="rd-dropdown-item">@Html.NavigationLink("App & system", "App", "Services", "rd-dropdown-link")</li>


                                    <li class="rd-dropdown-item">  @Html.NavigationLink("Webbplats", "Index", "Services", "rd-dropdown-link")</li>

                                </ul>
                            </li>
                                <li class="rd-nav-item">@Html.NavigationLink("Senaste Projekt", "Index", "Portfolio", "rd-nav-link")</li>
                               
                               
                                <li class="rd-nav-item rd-navbar--has-dropdown rd-navbar-submenu">
                                    
                                    <a class="rd-nav-link" href="#">Produkter</a>
                                    <!-- RD Navbar Dropdown-->
                                    <ul class="rd-menu rd-navbar-dropdown">
                                        <li class="rd-dropdown-link"> @Html.NavigationLink("CMS", "CMSinfo", "Features", "rd-dropdown-link")</li>
                                        <li class="rd-dropdown-link"> @Html.NavigationLink("Timeo", "Index", "Features", "rd-dropdown-link")</li>

                                    </ul>
                                </li>
                                <li class="rd-nav-item">
                                    @Html.NavigationLink("Kontakt", "Index", "Contact", "rd-nav-link")
                                </li>
                            </ul>

                            <div class="rd-navbar-element rd-navbar-element_centered">
                                <div class="group-xs">
                                    <a class="icon icon-sm link-social-2 mdi mdi-facebook" href="javascript:;"></a>
                                    <a class="icon icon-sm link-social-2 mdi mdi-linkedin" href="javascript:;"></a>
                                    <a class="icon icon-sm link-social-2 mdi mdi-instagram" href="https://www.instagram.com/optimize.ab" target="_blank"></a>
                                </div>
                            </div>
                        </div>
                        <div class="rd-navbar-element rd-navbar-element_right">
                            @*<ul class="list-localization">

                                <li>
                                    <label>
                                        <input name="localization" value="en" type="radio" checked="checked" /><span class="label-text">EN</span>
                                    </label>
                                </li>
                                <li>
                                    <label>
                                        <input name="localization" value="se" type="radio" /><span class="label-text">SW</span>
                                    </label>
                                </li>
                            </ul>*@
                        </div>
                        <div class="rd-navbar-dummy"></div>
                    </div>
                </nav>
            </div>
        </header>
        @RenderBody()
        <!-- Page Footer-->
        <footer class="section footer-classic">
            <div class="footer-classic-main">
                <div class="container">
                    <div class="row row-50 justify-content-lg-between">
                        <div class="col-sm-7 col-lg-3 col-xl-3">
                            <a class="brand" href="/Home"><img class="brand-logo-dark" src="~/Content/images/bluegradient logo.png" alt="" width="134"  /></a>
                            <p class="rights"><span>&copy;&nbsp; </span><span class="copyright-year"></span><span>&nbsp;</span><span>OPTIMIZE</span><span>.&nbsp;</span>@Html.ActionLink("Privacy Policy", "Index", "Policy")</p>

                        </div>
                        <div class="col-sm-5 col-lg-3 col-xl-3">
                            <h4 class="footer-classic-title">About</h4>
                            <ul class="list footer-classic-list">
                                <li>@Html.ActionLink("About Us", "Index", "About")</li>
                                <li>@Html.ActionLink("Sample Work", "Index", "Portfolio")</li>
                                <li>@Html.ActionLink("Privacy Policy", "Index", "Policy")</li>
                            </ul>
                        </div>
                        <div class="col-sm-7 col-lg-3 col-xl-3">
                            <h4 class="footer-classic-title">Services</h4>
                            <ul class="list footer-classic-list footer-classic-list_2-cols">
                                <li>@Html.ActionLink("Services", "Index", "Services")</li>
                                <li>@Html.ActionLink("Product", "Index", "Features")</li>
                                <li>@Html.ActionLink("Contact", "Index", "Contact")</li>
                            </ul>
                        </div>
                        <div class="col-sm-5 col-lg-3 col-xl-3">
                            <h4 class="footer-classic-title">Contacts</h4>
                            <div class="row row-20 row-sm-35">
                                <div class="col-6 col-sm-12 col-lg-8 col-xl-12">
                                    <div class="row row-10 text-default">
                                        <div class="col-lg-6 col-xl-12"><a href="mailto:info@optimizeab.com" target="_blank">info@optimizeab.com</a></div>
                                        <div class="col-lg-6 col-xl-12"><a class="big" href="tel:#">+46 762768302</a></div>
                                    </div>
                                </div>
                                <div class="col-6 col-sm-12 col-lg-4 col-xl-12 text-right text-sm-left">
                                    <div class="group group-xs"><a class="link link-social-1 mdi mdi-linkedin" href="javascript:;" target="_blank"></a><a class="link link-social-1 mdi mdi-facebook" href="javascript:;" target="_blank"></a><a class="link link-social-1 mdi mdi-instagram" href="https://www.instagram.com/optimize.ab" target="_blank"></a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </footer>
    </div>
    <div class="snackbars" id="form-output-global"></div>

    @Scripts.Render("~/bundles/script")
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-167621912-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-167621912-1');
    </script>

</body>
</html>