Optimize/Areas/Admin/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CMS.Facade;
using CMS.Dto;


namespace Optimize.Areas.Admin.Controllers
{
    public class ContactsController : Controller
    {
        ContactFacade _contacts = new ContactFacade();
        // GET: Admin/Contacts
        public ActionResult Index()
        {
            var data = _contacts.GetAllContacts();
            return View(data);
        }

        [HttpPost]
        public JsonResult SaveMessage(ContactDto dto)
        {
            var data = _contacts.SaveContactMsg(dto);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Details(long id)
        {
            var data = _contacts.LoadContact((long)id);
            return View(data);
        }

        public JsonResult RemoveMessage(long id)
        {
            var data = _contacts.DeleteHTML(id);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
    }
}

Optimize/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Optimize.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }
    }
}

Optimize/Areas/Admin/Views/Contacts/Details.cshtml
@model CMS.Dto.ContactDto
@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_DashboardLayout.cshtml";
}

<div class="page-content--bgf7 main-content">

    <!-- END BREADCRUMB-->
    <!-- WELCOME-->
    <section class="welcome p-t-10">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="title-4">
                      Request Message Details
                    </h1>
                    <hr class="line-seprate">
                </div>
            </div>
            <div class="row">
                <div class="col-md-8">
                    <div class="au-breadcrumb-content">
                        <div class="au-breadcrumb-left">
                            <span class="au-breadcrumb-span">You are here:</span>
                            <ul class="list-unstyled list-inline au-breadcrumb__list">
                                <li class="list-inline-item">
                                    @Html.ActionLink("Home", "Index", "Home")

                                </li>
                                <li class="list-inline-item seprate">
                                    <span>></span>
                                </li>
                                <li class="list-inline-item">More Information</li>

                            </ul>
                        </div>

                    </div>
                </div>
                <div class="col-md-4">
                    <a href='@Url.Action("Index", "Contacts")'>Back to List</a>
                </div>
            </div>
        </div>
    </section>
    <section class="statistic">
        <div class="container">
            <form>
                <div class="col-lg-10">
                    <div class="card">
                        <div class="card-header">
                            <strong>Message Details</strong>
                        </div>
                        <div class="card-body card-block">
                            <dl class="dl-horizontal">
                                <dt>
                                    @Html.DisplayName("Request Type")
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Subject)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model=>model.Name)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Name)
                                </dd>

                                <dt>
                                    @Html.DisplayNameFor(model => model.Email)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Email)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.Phone)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Phone)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.Message)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Message)
                                </dd>
                                <dt>
                                    @Html.Display("Request Date")
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.AddedDateText)
                                </dd>


                            </dl>

                        </div>
                        <div class="card-footer">
                            <p>
                                <a href='@Url.Action("Index", "Contacts")'>Back to List</a>
                            </p>
                        </div>
                    </div>

                </div>

            </form>

        </div>

    </section>
</div>

Optimize/Areas/Admin/Views/Contacts/Index.cshtml
@model IEnumerable<CMS.Dto.ContactDto>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_DashboardLayout.cshtml";
}

<div class="page-content--bgf7 main-content">

    <!-- END BREADCRUMB-->
    <!-- WELCOME-->
    <section class="welcome p-t-10">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="title-4">
                        All Contact Requests
                    </h1>
                    <hr class="line-seprate">
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="au-breadcrumb-content">
                        <div class="au-breadcrumb-left">
                            <span class="au-breadcrumb-span">You are here:</span>
                            <ul class="list-unstyled list-inline au-breadcrumb__list">
                                <li class="list-inline-item active">
                                    <a href="#">Home</a>
                                </li>
                                <li class="list-inline-item seprate">
                                    <span>/</span>
                                </li>
                                <li class="list-inline-item">Contact Messages</li>
                            </ul>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- END WELCOME-->
    <section class="statistic">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <!-- DATA TABLE -->

                    
                    <div class="table-responsive table-responsive-data2">
                        <table class="table table-data2">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Request Type</th>
                                    <th>Contact Details</th>
                                    <th>Message</th>
                                    <th>Request Date</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr class="tr-shadow">
                                        <td>@Html.DisplayFor(modelItem=> item.Subject)</td>
                                        <td>@Html.DisplayFor(modelItem => item.FullName)</td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Email) <br />
                                            @Html.DisplayFor(modelItem => item.Phone)
                                        </td>
                                        <td>@Html.DisplayFor(modelItem => item.Message)</td>

                                        <td>
                                            @Html.DisplayFor(modelItem => item.AddedDateText)
                                        </td>

                                        <td>
                                            <div class="table-data-feature">
                                                
                                                <button onclick="DeleteContact(@item.ContactId)" class="item" data-toggle="tooltip" data-placement="top" title="Delete">
                                                    <i class="zmdi zmdi-delete"></i>
                                                </button>

                                                <button class="item" onclick="location.href='@Url.Action("Details", "Contacts",new { id = item.ContactId })';return false;" data-toggle="tooltip" data-placement="top" title="Details">
                                                    <i class="zmdi zmdi-more"></i>
                                                </button>

                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <!-- END DATA TABLE -->
                </div>
            </div>
        </div>
        <div id="successModal" class="modal fade" role="dialog">
            <div class="modal-dialog modal-sm">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Response</h4>
                    </div>
                    <div class="modal-body" align="center">
                        <p id="successModalText"></p>
                        <button type="button" class="btn btn-success" data-dismiss="modal">Ok</button>
                    </div>
                    <div class="modal-footer">
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
        DeleteContact = function (id) {
           
            $.ajax({
                type: "POST",
                url: '/Admin/Contacts/RemoveMessage',
                data: {id:id},
                DataType: 'json',
                success: function (data) {
                    $('#successModal').modal('show');
                    $('#successModalText').text(data.Message);

                },
                error: function () {
                    $('#successModal').modal('show');
                    $('#successModalText').text(error.status + "<--save and--> " + error.statusText);

                }
            });
        }


    </script>
</div>